spring:
  application:
    name: "order"
  datasource:
    driver-class-name: ${yml.file.datasource.driver}
    username: ${yml.file.datasource.username}
    url: ${yml.file.datasource.url}
    password: ${yml.file.datasource.password}
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: none
    show-sql: "true"
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: "true"

# server
server:
  port: 8080
